apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::336684308047:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1S9ZNKG06ZWF1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::336684308047:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-10T04:24:39Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:mapRoles: {}
          f:mapUsers: {}
      manager: eksctl.exe
      operation: Update
      time: "2021-01-10T04:24:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1574"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b8e2f5a3-f9be-43da-84b5-a991dd06d3f4
